import numpy as np
n=np.arange(15).reshape(3,5)
n

In [9]:
n.shape

(3, 5)

In [11]:
n.ndim

2

In [13]:
n.size

15

In [17]:
type(n)

numpy.ndarray

In [19]:
n.dtype

dtype('int32')

In [33]:
a=np.array([1,2,3,4,4.2,56,3.3,'Sohaib'])
a

array(['1', '2', '3', '4', '4.2', '56', '3.3', 'Sohaib'], dtype='<U32')

In [29]:
a.dtype

dtype('float64')

# Two dimentional Array

In [55]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
b.dtype

dtype('int32')

In [61]:
c=np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [65]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.empty((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
d=np.empty((3,3))
d[2]=12
d

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [12., 12., 12.]])

In [91]:
s=np.arange(10,50,5)
s

array([10, 15, 20, 25, 30, 35, 40, 45])

In [101]:
s1=np.arange(1,2,0.025)
s1

array([1.   , 1.025, 1.05 , 1.075, 1.1  , 1.125, 1.15 , 1.175, 1.2  ,
       1.225, 1.25 , 1.275, 1.3  , 1.325, 1.35 , 1.375, 1.4  , 1.425,
       1.45 , 1.475, 1.5  , 1.525, 1.55 , 1.575, 1.6  , 1.625, 1.65 ,
       1.675, 1.7  , 1.725, 1.75 , 1.775, 1.8  , 1.825, 1.85 , 1.875,
       1.9  , 1.925, 1.95 , 1.975])

In [103]:
s2=np.linspace(0, 2, 9)
s2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [113]:
from numpy import pi
s3=np.linspace(0,2*pi,100)
s4=np.sin(s3)
s4

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# Printing arrays

In [6]:
import numpy as np
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
a1=np.arange(12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
a2=np.arange(80).reshape(2,5,8)
a2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63],
        [64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79]]])

In [58]:
a3=np.arange(10000).reshape(100,100)
a3

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

# Basic operations


In [65]:
b=np.arange(20).reshape(4,5)
b
b1=np.array([[1,2,3,4,5],[ 9,8,7,6,5],[ 3,4,5,6,7],[ 9,1,4,5,8]])
b1

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5],
       [3, 4, 5, 6, 7],
       [9, 1, 4, 5, 8]])

In [67]:
b+b1

array([[ 1,  3,  5,  7,  9],
       [14, 14, 14, 14, 14],
       [13, 15, 17, 19, 21],
       [24, 17, 21, 23, 27]])

In [69]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
b-b1

array([[-1, -1, -1, -1, -1],
       [-4, -2,  0,  2,  4],
       [ 7,  7,  7,  7,  7],
       [ 6, 15, 13, 13, 11]])

In [79]:
c=b**2
c

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [81]:
c>100

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [83]:
12*np.sin(b)

array([[  0.        ,  10.09765182,  10.91156912,   1.6934401 ,
         -9.08162994],
       [-11.5070913 ,  -3.35298598,   7.88383918,  11.87229896,
          4.94542182],
       [ -6.52825333, -11.99988248,  -6.43887502,   5.04200444,
         11.88728827],
       [  7.80345408,  -3.4548398 , -11.5367699 ,  -9.01184696,
          1.79852652]])

In [93]:
n=np.random.rand(4,4)
n

array([[0.9705164 , 0.20395124, 0.55037997, 0.41153667],
       [0.15045583, 0.35861506, 0.60971232, 0.17903737],
       [0.83610403, 0.01669833, 0.4075769 , 0.23173918],
       [0.49400671, 0.87530841, 0.17104962, 0.97816829]])

In [95]:
n

array([[0.9705164 , 0.20395124, 0.55037997, 0.41153667],
       [0.15045583, 0.35861506, 0.60971232, 0.17903737],
       [0.83610403, 0.01669833, 0.4075769 , 0.23173918],
       [0.49400671, 0.87530841, 0.17104962, 0.97816829]])

In [105]:
n1=np.ones((3,4),dtype=int)
n1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [111]:
n=np.arange(20).reshape(5,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [113]:
np.sum(n)

190

In [115]:
np.max(n)

19

In [117]:
np.min(n)

0

# univerl function

In [120]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
np.sqrt(m)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [126]:
np.exp(m)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])